Blocks Routes. Api v1
ergoplatform/explorer-backend pull request #124
Opened 2021-04-21 20:12 UTC by Bromel777

2021-04-26 15:15 UTC, oskin1 commented on modules/explorer-api/src/main/scala/org/ergoplatform/explorer/http/api/v1/models/BlockInfo.scala
> +)
Let's add `version` field to it.

2021-04-27 01:15 UTC, Bromel777 commented on modules/explorer-api/src/main/scala/org/ergoplatform/explorer/http/api/v1/models/BlockInfo.scala
> +)
done

2021-04-28 20:38 UTC, oskin1 commented on modules/explorer-api/src/main/scala/org/ergoplatform/explorer/http/api/v1/services/Blocks.scala
> +    F[_]: Sync,
We can do better and avoid Sync

2021-04-28 20:40 UTC, oskin1 commented on modules/explorer-api/src/main/scala/org/ergoplatform/explorer/http/api/v1/services/Blocks.scala
> +    F[_]: Sync,
Please refer to other services for stream compilation examples.

2021-05-01 09:24 UTC, oskin1 requested changes
Let's reuse unchanged models from APIv0 as much as possible.

2021-05-11 09:10 UTC, merged