Unconfirmed balance wrong when a payment is made #141
ergoplatform/explorer-backend pull request #177
Opened 2022-01-30 10:32 UTC by monyedavid

- getUnconfirmedBalance by considering Mempool

2022-02-02 15:35 UTC, aslesarenko commented on modules/explorer-api/src/main/scala/org/ergoplatform/explorer/http/api/v1/services/Mempool.scala
> +    }
Please implement tests for these two methods.

2022-02-03 09:54 UTC, oskin1 reviewed
Please move balance arithmetics to a separate module and cover it with tests.

2022-04-11 12:44 UTC, oskin1 requested changes

2022-04-11 12:44 UTC, oskin1 commented on modules/explorer-api/src/main/scala/org/ergoplatform/explorer/http/api/v1/services/Mempool.scala
> +    ): F[TotalBalance] = {
@monyedavid Why making one service method relying on another?
`confirmedBalanceOf(addr) >>=  getUnconfirmedBalanceByAddress(addr, _)`
Why not making both methods independently compute their part of `TotalBalance` and then construct TotalBalance from those parts in a separate `TotalBalance.apply(confirmed, unconfirmed)` smart constructor?

2022-05-12 08:07 UTC, closed without merging