Get confirmed + unconfirmed unspent boxes EP
ergoplatform/explorer-backend pull request #246
Opened 2022-10-31 18:34 UTC by semyonoskin

#245

2022-11-01 09:25 UTC, oskin1 requested changes

2022-11-01 09:25 UTC, oskin1 commented on modules/explorer-api/src/main/scala/org/ergoplatform/explorer/http/api/v1/services/Boxes.scala
> +        nUnonfirmed <- uoutputs.sumUnspentByErgoTree(ergoTree)
```suggestion
        nUnсonfirmed <- uoutputs.sumUnspentByErgoTree(ergoTree)
```

2022-11-01 09:25 UTC, oskin1 commented on modules/explorer-api/src/main/scala/org/ergoplatform/explorer/http/api/v1/services/Boxes.scala
> +        nUnonfirmed <- uoutputs.sumUnspentByErgoTree(ergoTree)
Please look careful at what `sumUnspentByErgoTree` really does
https://github.com/ergoplatform/explorer-backend/blob/44c1acbc3d0347eec17b2c2e5216ae5e23181d78/modules/explorer-core/src/main/scala/org/ergoplatform/explorer/db/queries/UOutputQuerySet.scala#L191

2022-11-01 09:25 UTC, oskin1 commented on modules/explorer-api/src/main/scala/org/ergoplatform/explorer/http/api/v1/services/Boxes.scala
> +                         )
So it seems your paging doesn't work as it should here. You retrieve a slice of expected number of confirmed outputs `streamUnspentByErgoTree(ergoTree, paging.offset, paging.limit, ord.value)` and then concatenate it with unknown number of unconfirmed outputs.

2022-11-11 12:46 UTC, oskin1 commented on modules/explorer-core/src/main/scala/org/ergoplatform/explorer/db/queries/UOutputQuerySet.scala
> +         |  o.value,
Please indent SQL

2022-11-11 12:46 UTC, oskin1 commented on modules/explorer-api/src/main/scala/org/ergoplatform/explorer/http/api/v1/defs/BoxesEndpointDefs.scala
> +      .out(jsonBody[Items[UOutputInfo]])
Let's not shrink `OutputInfo` down to `UOutputInfo` (omitting some fields). I'd suggest adding new coproduct that contains both variants (`AnyOutputInfo = OutputInfo | UOutputInfo`).

2022-11-23 09:42 UTC, oskin1 approved these changes

2022-11-29 18:49 UTC, GusevTimofey commented
https://github.com/ergoplatform/explorer-backend/blob/master/modules/explorer-api/src/main/scala/org/ergoplatform/explorer/http/api/v1/defs/BoxesEndpointDefs.scala#L133

may help you and can be used as reference

2022-12-19 11:42 UTC, merged